services:
  - type: web
    name: ghepvideo
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_PATH
        value: python3
    healthCheckPath: /
